version: '3.5'
services:
  db:
    container_name: db
    image: "postgres:14.1"
    restart: "unless-stopped"
    ports:
      - "5432:5432"
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=db_library
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_library
  backend:
    container_name: backend
    image: "library_app"
    depends_on:
      - db
    ports:
      - "7777:7777"
    restart: on-failure
    links:
      - db
#    environment:
#      - spring.datasource.url=jdbc:oracle:thin:@db:1521:ORCLCDB
#      - spring.datasource.username=SYS AS SYSDBA
#      - spring.datasource.password=Oradoc_db1