# The language we use
language: java

# Java Development Kit (JDK)
jdk:
  - openjdk8

dist: trusty

services:
  - docker

#before_install:
#  - docker-compose up

script:
  - pwd
  - cd library/library-backend/library-app/src/main/Docker
  - docker-compose up
  - mvn clean install

branches:
  only:
    - Travis-CI