# The language we use
language: java

# Java Development Kit (JDK)
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker-compose up

script:
  - mvn clean install

branches:
  only:
    - Travis-CI