# The language we use
language: java

# Java Development Kit (JDK)
jdk:
  - openjdk8

dist: trusty

services:
  - docker

#before_install:
#  - docker-compose pull db
#  - docker-compose up db

script:
  - docker --version
  - docker-compose --version
  - pwd
  - ls
  - cd library
  - ls
  - cd library-backend
  - ls
  - cd library-app
  - ls
  - cd src
  - ls
  - cd main
  - ls
  - cd Docker
  - ls
  - docker-compose pull db
  - mvn clean install

branches:
  only:
    - Travis-CI