version: '3.5'
services:
  db:
    container_name: db
    image: "store/oracle/database-enterprise:12.2.0.1-slim"
    restart: "unless-stopped"
    ports:
      - "1521:1521"
  backend:
    container_name: backend
    image: "library_app"
    depends_on:
      - db
    ports:
      - "7777:7777"
    restart: on-failure
    links:
      - db
    volumes:
      - ./data:/ORCL/u01
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@db:1521:ORCLCDB
      - spring.datasource.username=SYS AS SYSDBA
      - spring.datasource.password=Oradoc_db1